baseURL = 'https://rishat.space/'
languageCode = 'en-us'
title = 'Rishat Sultanov | Space'
theme = 'rishat-portfolio'

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

# navigation
[menu]
  [[menu.main]]
  name = "About"
  URL = "about"
#  [[menu.main]]
#  name = "Portfolio"
#  URL = "https://wiki.rishat.space"
  [[menu.main]]
  name = "CV"
  URL = "https://rishats.github.io/cv.github.io/"
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  [[menu.main]]
  name = "Contact"
  URL = "contact"

[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "The website of Rishat Sultanov, DevOps engineer from Almaty"
author = "Rishat Sultanov"


  [params.contact]
  formAction = "https://formspree.io//f/mdobzlnd" # Add your formspree URL here to get emails

  # This contains the contact information for the footer
  [params.footer]
  email = "rihasultanov@gmail.com"
  address = "Asia, Almaty"
  googlemaps = "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwbHYJaUqfEgRK0Ui9dVGimc&key=AIzaSyCaBbBuK14eElvJGA8-gLrCWOyyP86eQyA"
